name: ddd_annotations
description: A sample command-line application.
version: 1.0.0
repository: github.com/simplifit-michael/ddd_annotations.git
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'
